### ISSUE TITLE
The tooltip buttons are not shown

### ISSUE THREAD

**Issue by MarianoFacundoArch** [patricktran/shaka-player-ui-controls#1]
Can we add them? 

Here is a sample on how to add them:

https://github.com/shaka-project/shaka-player/pull/3572/files

Basically:
```
 this.button.classList.add('shaka-tooltip-status');
 this.button.setAttribute('shaka-status', "Text of tooltip");
```

**Comment by patricktran** [comment]
I will look into this, thank you.

**Comment by patricktran** [comment]
Sorry for the long wait, but tooltips are supported in v1.0.11
